import { APP_BRAND_MARK } from "@/theme/appBrand";

export const strings = {
  camera: {
    errors: {
      noPhotoToSave: "No photo to save",
      failedToSavePhoto: "Failed to save photo",
      galleryPermissionRequired: "We need gallery access to pick photos.",
    },
    info: {
      photoAlreadySaved: "Photo already saved",
      photoCaptured: "Photo captured",
      photoSelected: "Photo selected",
    },
    success: {
      quoteGenerated: "Quote generated",
      photoSaved: "Photo saved",
    },
  },
  memories: {
    title: "Memories",
    thisDayInMemoriesLabel: "This day in memories",
    emptyForDay: "No memories for this day yet.",
    friendsPlaceholder: "Friends' memories will appear here.",
    publicPlaceholder: "Public memories will appear here.",
  },
  home: {
    cameraPermissionRequired: "We need camera access to take photos.",
    inviteFriendsTitle: `Invite friends on ${APP_BRAND_MARK}`,
    inviteSkip: "Skip",
    inviteCta: "Invite",
    messagePlaceholder: "Send a message…",
    messageSent: "Message sent",
    savedToMemories: "Saved to your memories",
    luckLabel: "Luck",
    vibes: {
      dawn: "Dawn",
      mist: "Mist",
      coral: "Coral",
      indigo: "Indigo",
      forest: "Forest",
      ember: "Ember",
      sage: "Sage",
      midnight: "Midnight",
      aurora: "Aurora",
      prism: "Prism",
    },
    vibeRarity: {
      common: "Common",
      uncommon: "Uncommon",
      rare: "Rare",
      superRare: "Super Rare",
      superLegend: "Super Legend",
    },
    vibeRarityShort: {
      common: "C",
      uncommon: "U",
      rare: "R",
      superRare: "SR",
      superLegend: "★",
    },
    momentsFeed: {
      watermarkBrand: APP_BRAND_MARK,
      watermarkTagline: "Daily vibes",
      momentEyebrow: "Moment",
      shareMomentA11y: "Share this moment with branding",
    },
  },
  subscription: {
    aiLimitReachedTitle: "You reached today’s free AI limit.",
    aiLimitReachedBody: "Upgrade to Pro for unlimited quote generations.",
    personaLockedTitle: "This persona needs Pro.",
    personaLockedBody: "Upgrade to unlock advanced persona controls.",
    paywallHeroTitle: "Create better quote cards without limits",
    paywallHeroSubtitle: "Unlimited quotes, exports, and premium styles.",
    paywallBullet1: "Generate as many AI quotes as you want — no daily cap.",
    paywallBullet2: "Export and share quote cards without limits.",
    paywallBullet3: "Unlock every theme and remove the watermark.",
    aiLimitPaywallBody:
      "You’ve used today’s free generations. Pro unlocks unlimited AI quotes so you never hit a wall.",
    exportLimitPaywallBody:
      "You’ve reached today’s export limit. Pro lets you export and share as many cards as you want.",
    premiumThemePaywallBody:
      "Pro opens every premium layout and style so your cards always look polished.",
    personaPaywallBody:
      "Pro unlocks full persona controls so the AI matches your voice.",
    featureHeader: "What you get",
    featureHeaderHighlight: "Compare plans",
    featureDailyQuotes: "Daily AI vibes",
    featureExports: "Daily exports",
    featurePremiumThemes: "Premium themes",
    featureAdvancedPersona: "Advanced persona tuning",
    featureWatermark: `${APP_BRAND_MARK} watermark`,
    freeLabel: "Free",
    proLabel: "Pro",
    freeDailyQuotesValue: "3 / day",
    proDailyQuotesValue: "Unlimited",
    freeExportsValue: "3 / day",
    proExportsValue: "Unlimited",
    freePremiumThemesValue: "Locked",
    proPremiumThemesValue: "All styles",
    freeAdvancedPersonaValue: "Basic only",
    proAdvancedPersonaValue: "Full control",
    freeWatermarkValue: "Shown",
    proWatermarkValue: "Removed",
    heroEyebrow: "Unlock everything",
    choosePlanHeader: "Choose your plan",
    noPlansAvailable:
      "We couldn’t load subscription plans. Check your connection and try again, or open the App Store / Play Store and try later.",
    primaryCta: "Continue",
    processingCta: "Processing…",
    restoreCta: "Restore purchases",
    maybeLaterCta: "Not now",
    bestValueTag: "Best value",
    purchaseSuccessToast: "Subscription active — you’re on Pro now.",
    purchaseVerifyLater:
      "Purchase received. If Pro doesn’t unlock in a minute, tap Restore purchases.",
    restoreSuccessToast: "Pro restored — your subscription is active.",
    restoreNoActiveToast: "No active subscription found for this account.",
    subscriptionTermsLink: "Terms of Use",
    privacyPolicyLink: "Privacy Policy",
    footerReassurance:
      "Payments are processed by Apple or Google. You can cancel anytime in Settings.",
    statusLoadingPlansTitle: "Connecting to the store…",
    statusLoadingPlansBody:
      "We’re fetching live prices and plans from Apple or Google. This usually takes a few seconds.",
    statusPurchasingTitle: "Completing your purchase…",
    statusPurchasingBody:
      "Stay on this screen. You may be asked to confirm with Face ID, Touch ID, or your store password.",
    statusRestoringTitle: "Restoring your purchases…",
    statusRestoringBody:
      "We’re checking your account for an active subscription. This may take a moment.",
    statusErrorTitle: "Something went wrong",
    retryLoadPlans: "Try again",
    ctaHelperIos: "You’ll confirm with Face ID, Touch ID, or your Apple ID.",
    ctaHelperAndroid: "You’ll confirm with your Google Play account on the next screen.",
    contextAiLimitTitle: "Generate quotes anytime",
    contextExportLimitTitle: "Export without limits",
    contextPremiumThemeTitle: "Unlock premium styles",
    contextPersonaLockedTitle: "Unlock advanced persona",
    contextGenericTitle: "Upgrade to Pro",
  },
}
