export const strings = {
  camera: {
    errors: {
      noPhotoToSave: "No photo to save",
      failedToSavePhoto: "Failed to save photo",
      galleryPermissionRequired: "We need gallery access to pick photos.",
    },
    info: {
      photoAlreadySaved: "Photo already saved",
      photoCaptured: "Photo captured",
      photoSelected: "Photo selected",
    },
    success: {
      quoteGenerated: "Quote generated",
      photoSaved: "Photo saved",
    },
  },
  memories: {
    title: "Memories",
    thisDayInMemoriesLabel: "This day in memories",
    emptyForDay: "No memories for this day yet.",
    friendsPlaceholder: "Friends' memories will appear here.",
    publicPlaceholder: "Public memories will appear here.",
  },
  home: {
    cameraPermissionRequired: "We need camera access to take photos.",
    inviteFriendsTitle: "Invite friends to share quotes with",
    inviteSkip: "Skip",
    inviteCta: "Invite",
    messagePlaceholder: "Send a message…",
    messageSent: "Message sent",
    savedToMemories: "Saved to your memories",
  },
  subscription: {
    aiLimitReachedTitle: "You reached today’s free AI limit.",
    aiLimitReachedBody: "Upgrade to Pro for unlimited quote generations.",
    paywallHeroTitle: "Create better quote cards without limits",
    paywallHeroSubtitle: "Unlimited quotes, exports, and premium styles.",
    featureHeader: "What you get",
    featureDailyQuotes: "Daily AI quotes",
    featureExports: "Daily exports",
    featurePremiumThemes: "Premium themes",
    featureAdvancedPersona: "Advanced persona tuning",
    featureWatermark: "App watermark",
    freeLabel: "Free",
    proLabel: "Pro",
    freeDailyQuotesValue: "3 / day",
    proDailyQuotesValue: "Unlimited",
    freeExportsValue: "3 / day",
    proExportsValue: "Unlimited",
    freePremiumThemesValue: "Locked",
    proPremiumThemesValue: "All styles",
    freeAdvancedPersonaValue: "Basic only",
    proAdvancedPersonaValue: "Full control",
    freeWatermarkValue: "Shown",
    proWatermarkValue: "Removed",
    choosePlanHeader: "Choose your plan",
    primaryCta: "Continue",
    processingCta: "Processing…",
    restoreCta: "Restore purchases",
    maybeLaterCta: "Not now",
    bestValueTag: "Best value",
    purchaseSuccessToast: "Welcome to Pro — enjoy unlimited quotes.",
    restoreSuccessToast: "Your Pro access is restored.",
    restoreNoActiveToast: "No active subscription found for this account.",
    subscriptionTermsLink: "Terms of Use",
    privacyPolicyLink: "Privacy Policy",
    footerReassurance:
      "Payments are processed by Apple or Google. You can cancel anytime in Settings.",
    contextAiLimitTitle: "Generate quotes anytime",
    contextExportLimitTitle: "Export without limits",
    contextPremiumThemeTitle: "Unlock premium styles",
    contextPersonaLockedTitle: "Unlock advanced persona",
    contextGenericTitle: "Upgrade to Pro",
  },
}
